package com.pos.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class IdGenerator {

    private IdGenerator() {}

    public static String nextCustomerId(Connection connection) throws SQLException {
        return nextId(connection, "customer_seq", "C");
    }

    public static String nextItemCode(Connection connection) throws SQLException {
        return nextId(connection, "item_seq", "I");
    }

    public static String nextOrderId(Connection connection) throws SQLException {
        return nextId(connection, "order_seq", "O");
    }

    private static String nextId(Connection connection, String sequenceName, String prefix) throws SQLException {
        String sql = "SELECT nextval('" + sequenceName + "')";
        try (PreparedStatement ps = connection.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            rs.next();
            return String.format("%s%03d", prefix, rs.getInt(1));
        }
    }
}

/*
*
* ou don't need IdGenerator because it's legacy JDBC code that's been replaced by different ID generation strategies.

What It Does (Legacy JDBC)


java
public static String nextCustomerId(Connection connection) throws SQLException {
    return nextId(connection, "customer_seq", "C");  // Uses PostgreSQL sequence
}
It uses PostgreSQL sequences (customer_seq, item_seq, order_seq) to generate IDs like C001, I001, O001.

Why It's Not Used Now
1. Customer & Item IDs - Generated by client/frontend

The frontend generates IDs before sending requests
Controllers validate the format with regex patterns
No backend ID generation needed
2. Order IDs - Generated in OrderService



java
private String generateOrderId() {
    List<OrderEntity> allOrders = orderRepository.findAll();
    return "O" + (allOrders.size() + 1);  // Simple count-based
}
3. No JDBC connections - The application now uses:

Hibernate/JPA for database operations
Spring Data JPA repositories
No direct JDBC connections
4. Sequences not used - The PostgreSQL sequences (customer_seq, item_seq, order_seq) are created by the legacy Database class but never used by the current Hibernate setup.

Current ID Generation Summary
Entity	ID Generation	Location
Customer	Client/frontend	React app generates C001, C002...
Item	Client/frontend	React app generates I001, I002...
Order	Service layer	OrderService.generateOrderId()
Delete IdGenerator.java along with Database.java - both are from the old JDBC implementation that's been replaced by Hibernate/JPA.
* */

