package com.pos.service;

import com.pos.dto.CustomerDTO;
import com.pos.entity.CustomerEntity;
import com.pos.repository.CustomerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

/**
 * CustomerService - Business Logic Layer
 * Handles all customer-related operations using Spring Data JPA.
 * Hibernate handles CRUD operations and transaction management automatically.
 */
@Service
@Transactional
public class CustomerService {

    private static final Logger logger = Logger.getLogger(CustomerService.class.getName());

    @Autowired
    private CustomerRepository customerRepository;

    /**
     * Save a new customer
     * Customer ID is expected to be set in the DTO (auto-generated by the frontend/controller)
     */
    public CustomerDTO saveCustomer(CustomerDTO dto) {
        logger.info("Service: Saving customer: " + dto.getName());
        CustomerEntity entity = new CustomerEntity(
                dto.getId(), dto.getName(), dto.getAddress(), dto.getEmail());
        CustomerEntity saved = customerRepository.save(entity);
        logger.info("Service: Customer saved successfully with ID: " + saved.getId());
        return new CustomerDTO(saved.getId(), saved.getName(), saved.getAddress(), saved.getEmail());
    }

    /**
     * Update an existing customer
     */
    public CustomerDTO updateCustomer(CustomerDTO dto) {
        logger.info("Service: Updating customer: " + dto.getId());
        CustomerEntity entity = new CustomerEntity(
                dto.getId(), dto.getName(), dto.getAddress(), dto.getEmail());
        CustomerEntity updated = customerRepository.save(entity);
        logger.info("Service: Customer updated successfully: " + dto.getId());
        return new CustomerDTO(updated.getId(), updated.getName(), updated.getAddress(), updated.getEmail());
    }

    /**
     * Delete a customer by ID
     */
    public void deleteCustomer(String id) {
        logger.info("Service: Deleting customer: " + id);
        customerRepository.deleteById(id);
        logger.info("Service: Customer deleted successfully: " + id);
    }

    /**
     * Find a customer by ID
     */
    @Transactional(readOnly = true)
    public CustomerDTO findCustomer(String id) {
        return customerRepository.findById(id)
                .map(entity -> new CustomerDTO(entity.getId(), entity.getName(), entity.getAddress(), entity.getEmail()))
                .orElse(null);
    }

    /**
     * Find all customers
     */
    @Transactional(readOnly = true)
    public List<CustomerDTO> findAllCustomers() {
        logger.info("Service: Fetching all customers");
        List<CustomerDTO> dtos = new ArrayList<>();
        for (CustomerEntity entity : customerRepository.findAll()) {
            dtos.add(new CustomerDTO(entity.getId(), entity.getName(), entity.getAddress(), entity.getEmail()));
        }
        return dtos;
    }
}

