package com.pos.service;

import com.pos.dto.ItemDTO;
import com.pos.entity.ItemEntity;
import com.pos.repository.ItemRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

/**
 * ItemService - Business Logic Layer
 * Handles all item/product-related operations using Spring Data JPA.
 * Hibernate handles CRUD operations and transaction management automatically.
 */
@Service
@Transactional
public class ItemService {

    private static final Logger logger = Logger.getLogger(ItemService.class.getName());

    @Autowired
    private ItemRepository itemRepository;

    /**
     * Save a new item
     * Item code is expected to be set in the DTO (auto-generated by the frontend/controller)
     */
    public ItemDTO saveItem(ItemDTO dto) {
        logger.info("Service: Saving item: " + dto.getDescription());
        ItemEntity entity = new ItemEntity(
                dto.getCode(), dto.getDescription(), dto.getUnitPrice(), dto.getQtyOnHAnd());
        ItemEntity saved = itemRepository.save(entity);
        logger.info("Service: Item saved successfully with code: " + saved.getCode());
        return new ItemDTO(saved.getCode(), saved.getDescription(), saved.getUnitPrice(), saved.getQtyOnHAnd());
    }

    /**
     * Update an existing item
     */
    public ItemDTO updateItem(ItemDTO dto) {
        logger.info("Service: Updating item: " + dto.getCode());
        ItemEntity entity = new ItemEntity(
                dto.getCode(), dto.getDescription(), dto.getUnitPrice(), dto.getQtyOnHAnd());
        ItemEntity updated = itemRepository.save(entity);
        logger.info("Service: Item updated successfully: " + dto.getCode());
        return new ItemDTO(updated.getCode(), updated.getDescription(), updated.getUnitPrice(), updated.getQtyOnHAnd());
    }

    /**
     * Delete an item by code
     */
    public void deleteItem(String code) {
        logger.info("Service: Deleting item: " + code);
        itemRepository.deleteById(code);
        logger.info("Service: Item deleted successfully: " + code);
    }

    /**
     * Find an item by code
     */
    @Transactional(readOnly = true)
    public ItemDTO findItem(String code) {
        return itemRepository.findById(code)
                .map(entity -> new ItemDTO(entity.getCode(), entity.getDescription(), entity.getUnitPrice(), entity.getQtyOnHAnd()))
                .orElse(null);
    }

    /**
     * Find all items
     */
    @Transactional(readOnly = true)
    public List<ItemDTO> findAllItems() {
        logger.info("Service: Fetching all items");
        List<ItemDTO> dtos = new ArrayList<>();
        for (ItemEntity entity : itemRepository.findAll()) {
            dtos.add(new ItemDTO(entity.getCode(), entity.getDescription(), entity.getUnitPrice(), entity.getQtyOnHAnd()));
        }
        return dtos;
    }
}

